# Generated by Django 4.2.7 on 2023-12-08 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymrating',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='gymrating',
            name='user',
        ),
        migrations.DeleteModel(
            name='Gym',
        ),
        migrations.DeleteModel(
            name='GymRating',
        ),
    ]
