# Generated by Django 4.2.7 on 2023-12-22 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_gymrating_gym_remove_gymrating_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('education', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('years_of_experience', models.IntegerField()),
                ('description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoachInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('education', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('years_of_experience', models.IntegerField()),
                ('description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
