# Generated by Django 4.2.7 on 2023-12-07 21:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_alter_gym_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='rate',
        ),
        migrations.AlterField(
            model_name='gym',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='gyms.gym')),
            ],
        ),
    ]
