# Generated by Django 4.2.7 on 2023-12-08 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gyms', '0003_remove_gym_rate_alter_gym_name_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='city',
            field=models.CharField(default='YourDefaultCity', max_length=255),
        ),
        migrations.AddField(
            model_name='gym',
            name='coaches',
            field=models.ManyToManyField(limit_choices_to={'role': 'coach'}, related_name='coached_gyms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gym',
            name='manager',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_gym', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gym',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gym',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
