# Generated by Django 4.2.7 on 2023-12-14 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gyms', '0004_gym_city_gym_coaches_gym_manager_alter_gym_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='users',
            field=models.ManyToManyField(limit_choices_to={'role': 'user'}, related_name='gym_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
