# Generated by Django 4.2.9 on 2024-01-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymlist', '0002_customer_gyms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='tuition',
        ),
        migrations.AddField(
            model_name='customer',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='gym',
            name='tier1_tuition',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='gym',
            name='tier2_tuition',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='gym',
            name='tier3_tuition',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=10),
        ),
    ]
