# Generated by Django 4.2.9 on 2024-01-28 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymlist', '0003_remove_gym_tuition_customer_wallet_gym_tier1_tuition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='gyms',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='coaches',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gyms',
        ),
    ]
