# Generated by Django 4.2.9 on 2024-01-28 17:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymlist', '0004_remove_coach_customers_remove_coach_gyms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='gym',
            name='coaches',
            field=models.ManyToManyField(related_name='gyms', to='gymlist.coach'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='customers',
            field=models.ManyToManyField(related_name='gyms', to='gymlist.customer'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.AddField(
            model_name='gymrating',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='gymlist.gym'),
        ),
    ]
