# Generated by Django 4.2.9 on 2024-01-29 12:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymlist', '0005_gymrating_alter_gym_coaches_alter_gym_customers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='gymlist.coach')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
