# Generated by Django 4.2.9 on 2024-01-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymlist', '0006_coachrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='more_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='program1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='program2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='program3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='program4',
            field=models.TextField(null=True),
        ),
    ]
